FROM python:3.12-slim

WORKDIR /site

RUN pip install --no-cache-dir \
    mkdocs \
    mkdocs-material \
    pymdown-extensions

COPY . .

RUN mkdocs build

EXPOSE 8000

CMD ["python", "-m", "http.server", "8000", "--directory", "site"]
